workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    environment:
      groups:
        - ios
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.flaviusstanciu.naominails
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Capacitor sync
        script: npx cap sync ios
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --project ios/App/App.xcodeproj \
            --scheme App
    artifacts:
      - build/ios/ipa/*.ipa
